name: Testing the action

on: 
  push: 

  workflow_dispatch:
    
jobs:
  load-all-used-actions:
    runs-on: ubuntu-latest
    name: Test on current organization
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ env.GITHUB_REPOSITORY_OWNER }} 
        id: load-actions

      - name: Store output in result file
        run: echo '${{ steps.load-actions.outputs.actions }}' > 'actions.json'      
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions-${{ env.GITHUB_REPOSITORY_OWNER }}
          path: actions.json

  load-all-used-actions-other-org:
    runs-on: ubuntu-latest
    name: Test on different organization
    env:
      organization: rajbos-actions
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: ${{ env.organization }}
        id: load-actions

      - name: Store output in result file
        run: echo '${{ steps.load-actions.outputs.actions }}' > 'actions.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions-${{ env.organization }}
          path: actions.json